### ISSUE TITLE
Bring Explainer's Explainer to WICG

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/starter-kit#15]
https://docs.google.com/document/d/1cJs7GkdQolqOHns9k6v1UjCUb_LqTFVjZM-kc3TbNGI/edit?usp=sharing

**Comment by slightlyoff** [comment]
If/when you do this, can we get a link the the Spec template to the corresponding explainer as well? It's one of the first things we end up asking to see when reviewing specs at the TAG.

**Comment by jyasskin** [comment]
It's now in https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md, and should probably replace the content in https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md.

**Comment by marcoscaceres** [comment]
Copied the template from the TAG explainer. 

https://github.com/WICG/starter-kit/blob/master/templates/explainer.md
