### ISSUE TITLE
Should only require node 6

### ISSUE THREAD

**Issue by jyasskin** [WICG/starter-kit#18]
The current Node LTS is 6.11.3, but `package.json` says v7 is required, and indeed v6 fails on `async function performGitTasks(collectedData)`.

The starter kit shouldn't require people to install a Node version more recent than the LTS version.

**Comment by marcoscaceres** [comment]
That's fair, but Node 8 is going to [LTS in less than a month](https://github.com/nodejs/Release#release-schedule1) (October 2017). I would prefer we stick with the current code, and then adhere to the LTS release cycle going forward.

**Comment by jyasskin** [comment]
Yeah, sticking to it going forward seems like the right thing to do.
