### ISSUE TITLE
LICENSE template isn't correct for CG output

### ISSUE THREAD

**Issue by jyasskin** [WICG/starter-kit#19]
We should be using the https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document license, which permits modification, and should probably mention https://www.w3.org/community/about/agreements/cla/.

**Comment by marcoscaceres** [comment]
oh, good catch.

**Comment by marcoscaceres** [comment]
About mentioning the CLA... I'm not sure what to say there exactly. Maybe just?:

> All contributions made to this repository were made under the [Contributor License Agreement](https://www.w3.org/community/about/agreements/cla/). Please see also [CONTRIBUTING.md](CONTRIBUTING.md) for how to participate in this work.
