### ISSUE TITLE
Node version check seems not to work right

### ISSUE THREAD

**Issue by alvestrand** [WICG/starter-kit#4]
This package doesn't work at all on Node 4; it requires Node 6.
(at least that's how I interpreted the syntax error when I tried to run it on Node 4).

I think the package.json file was intended to say so too, it says 

"engines": {
    "node": ">= 6"
  },

But when I installed it on top of Node 4, no warning was given.
I'm not enough of an NPM expert to suggest a fix.

**Comment by marcoscaceres** [comment]
After some reading, there is not much I can do here without a big rewrite (or some ugly hacks). I added "engineStrict: true" to package.json, which will at least generate a warning in Node4. 

With regards to preventing installation, this is a user controlled option:
https://docs.npmjs.com/misc/config#engine-strict

Node 6 is going LTS in about a week, so will keep compatible with that:
https://github.com/nodejs/LTS
