### ISSUE TITLE
CONTRIBUTING file is incorrect for a CG spec

### ISSUE THREAD

**Issue by AmeliaBR** [WICG/starter-kit#42]
The generated CONTRIBUTING.md file (based on https://github.com/WICG/starter-kit/blob/master/templates/CONTRIBUTING.md) is based on a working group spec. E.g., it says “To contribute, you must either participate in the relevant W3C Working Group or make a non-member patent licensing commitment.”

The W3C recommended template for CG projects is https://github.com/w3c/licenses/blob/master/CG-CONTRIBUTING.md

**Comment by marcoscaceres** [comment]
Thanks, fixed.
